"""PDF Generator utility functions using ReportLab."""

from datetime import datetime
from io import BytesIO
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def create_pdf_header(canvas, title: str, mfd_name: str, date_str: str):
    """
    Create PDF header with logo, title, MFD name, and date.
    
    This is typically used with canvas.showPage() callbacks.
    """
    # Logo placeholder (you can add actual logo loading here)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(2 * cm, A4[1] - 2 * cm, "MFD Digital Diary")

    # Title
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawCentredString(A4[0] / 2, A4[1] - 3 * cm, title)

    # MFD Name and Date
    canvas.setFont("Helvetica", 10)
    canvas.drawString(2 * cm, A4[1] - 4 * cm, f"Prepared by: {mfd_name}")
    canvas.drawRightString(A4[0] - 2 * cm, A4[1] - 4 * cm, f"Date: {date_str}")

    # Horizontal line
    canvas.setStrokeColor(colors.grey)
    canvas.line(2 * cm, A4[1] - 4.5 * cm, A4[0] - 2 * cm, A4[1] - 4.5 * cm)


def create_pdf_footer(canvas, page_number: int):
    """Create PDF footer with page number and generation info."""
    canvas.setFont("Helvetica", 8)
    
    # Page number
    canvas.drawCentredString(A4[0] / 2, 1.5 * cm, f"Page {page_number}")
    
    # Generated by info
    canvas.drawString(2 * cm, 1 * cm, "Generated by MFD Digital Diary")
    
    # Generation timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    canvas.drawRightString(A4[0] - 2 * cm, 1 * cm, f"Generated: {timestamp}")


def create_table(
    data: List[List[str]], col_widths: List[float], has_header: bool = True
) -> Table:
    """
    Create a styled ReportLab Table.
    
    Args:
        data: List of rows, each row is a list of cell values
        col_widths: List of column widths in inches
        has_header: If True, first row is styled as header
    
    Returns:
        Styled Table object
    """
    table = Table(data, colWidths=[w * inch for w in col_widths])

    # Base style
    style_commands = [
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]

    # Header styling
    if has_header and len(data) > 0:
        style_commands.extend(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4472C4")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
            ]
        )

        # Alternating row colors (skip header)
        for i in range(1, len(data)):
            if i % 2 == 0:
                style_commands.append(
                    ("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F2F2F2"))
                )

    table.setStyle(TableStyle(style_commands))
    return table


def generate_goal_pdf(
    goal_data: Dict[str, Any], client_data: Dict[str, Any], mfd_name: str
) -> bytes:
    """Generate a goal planning PDF."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=5 * cm,
        bottomMargin=3 * cm,
    )

    # Container for PDF elements
    elements = []
    styles = getSampleStyleSheet()

    # Title
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#4472C4"),
        spaceAfter=20,
        alignment=1,  # Center
    )
    elements.append(Paragraph(f"Goal Planning Report", title_style))
    elements.append(Paragraph(f"{goal_data.get('goal_name', 'Financial Goal')}", title_style))
    elements.append(Spacer(1, 0.5 * cm))

    # Client Details Section
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor("#4472C4")
    )
    elements.append(Paragraph("Client Details", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    client_info = [
        ["Name:", client_data.get("name", "N/A")],
        ["Phone:", client_data.get("phone", "N/A")],
        ["Email:", client_data.get("email", "N/A")],
    ]
    client_table = create_table(client_info, [2, 4], has_header=False)
    elements.append(client_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Goal Details Section
    elements.append(Paragraph("Goal Details", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    goal_info = [
        ["Goal Type:", goal_data.get("goal_type", "N/A")],
        ["Target Amount:", f"₹ {goal_data.get('target_amount', 0):,.2f}"],
        ["Target Date:", str(goal_data.get("target_date", "N/A"))],
        ["Current Investment:", f"₹ {goal_data.get('current_investment', 0):,.2f}"],
        ["Progress:", f"{goal_data.get('progress_percent', 0):.1f}%"],
    ]
    goal_table = create_table(goal_info, [2, 4], has_header=False)
    elements.append(goal_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Investment Plan Section
    elements.append(Paragraph("Investment Plan", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    investment_info = [
        ["Monthly SIP:", f"₹ {goal_data.get('monthly_sip', 0):,.2f}"],
        ["Lumpsum Investment:", f"₹ {goal_data.get('lumpsum_investment', 0):,.2f}"],
        ["Expected Return:", f"{goal_data.get('expected_return_rate', 12):.1f}%"],
    ]
    investment_table = create_table(investment_info, [2, 4], has_header=False)
    elements.append(investment_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Product Allocation (if available)
    products = goal_data.get("products", [])
    if products:
        elements.append(Paragraph("Product Allocation", section_style))
        elements.append(Spacer(1, 0.2 * cm))

        product_data = [["Product Name", "Type", "Amount", "Expected Return"]]
        for product in products:
            product_data.append(
                [
                    product.get("name", "N/A"),
                    product.get("type", "N/A"),
                    f"₹ {product.get('amount', 0):,.2f}",
                    f"{product.get('return_rate', 0):.1f}%",
                ]
            )

        product_table = create_table(product_data, [2.5, 1.5, 1.5, 1.5])
        elements.append(product_table)
        elements.append(Spacer(1, 0.5 * cm))

    # Footer note
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            f"This goal plan has been prepared by {mfd_name}. "
            "Please review and confirm before proceeding.",
            footer_style,
        )
    )

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_mom_pdf(
    touchpoint_data: Dict[str, Any], client_data: Dict[str, Any], mfd_name: str
) -> bytes:
    """Generate Minutes of Meeting PDF."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=5 * cm,
        bottomMargin=3 * cm,
    )

    elements = []
    styles = getSampleStyleSheet()

    # Title
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#4472C4"),
        spaceAfter=20,
        alignment=1,
    )
    elements.append(Paragraph("Minutes of Meeting", title_style))
    elements.append(Spacer(1, 0.5 * cm))

    # Meeting Details
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor("#4472C4")
    )
    elements.append(Paragraph("Meeting Details", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    meeting_info = [
        ["Date:", str(touchpoint_data.get("scheduled_date", "N/A"))],
        ["Time:", str(touchpoint_data.get("scheduled_time", "N/A"))],
        ["Location:", touchpoint_data.get("location", "N/A")],
        ["Interaction Type:", touchpoint_data.get("interaction_type", "N/A")],
        ["Duration:", f"{touchpoint_data.get('duration_minutes', 0)} minutes"],
    ]
    meeting_table = create_table(meeting_info, [2, 4], has_header=False)
    elements.append(meeting_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Client Details
    elements.append(Paragraph("Client Details", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    client_info = [
        ["Name:", client_data.get("name", "N/A")],
        ["Phone:", client_data.get("phone", "N/A")],
        ["Email:", client_data.get("email", "N/A")],
    ]
    client_table = create_table(client_info, [2, 4], has_header=False)
    elements.append(client_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Agenda
    elements.append(Paragraph("Agenda", section_style))
    elements.append(Spacer(1, 0.2 * cm))
    agenda_text = touchpoint_data.get("agenda", "N/A")
    elements.append(Paragraph(agenda_text, styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    # Discussion Points / MoM
    elements.append(Paragraph("Discussion Points", section_style))
    elements.append(Spacer(1, 0.2 * cm))
    mom_text = touchpoint_data.get("mom_text", "No minutes recorded.")
    elements.append(Paragraph(mom_text.replace("\n", "<br/>"), styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    # Outcome
    if touchpoint_data.get("outcome"):
        elements.append(Paragraph("Outcome", section_style))
        elements.append(Spacer(1, 0.2 * cm))
        elements.append(Paragraph(touchpoint_data["outcome"], styles["Normal"]))
        elements.append(Spacer(1, 0.5 * cm))

    # Next Steps
    elements.append(Paragraph("Next Steps", section_style))
    elements.append(Spacer(1, 0.2 * cm))
    next_steps = touchpoint_data.get("notes", "Follow-up meeting to be scheduled.")
    elements.append(Paragraph(next_steps, styles["Normal"]))

    # Footer
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            f"Prepared by: {mfd_name}<br/>"
            f"Date: {datetime.now().strftime('%Y-%m-%d')}",
            footer_style,
        )
    )

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_calculator_pdf(
    calc_type: str,
    inputs: Dict[str, Any],
    outputs: Dict[str, Any],
    client_data: Dict[str, Any],
    mfd_name: str,
) -> bytes:
    """Generate calculator results PDF."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=5 * cm,
        bottomMargin=3 * cm,
    )

    elements = []
    styles = getSampleStyleSheet()

    # Title
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#4472C4"),
        spaceAfter=20,
        alignment=1,
    )
    calc_titles = {
        "sip": "SIP Calculator Results",
        "lumpsum": "Lumpsum Calculator Results",
        "retirement": "Retirement Planning Report",
        "education": "Education Planning Report",
        "insurance": "Insurance Needs Analysis",
    }
    elements.append(Paragraph(calc_titles.get(calc_type, "Financial Calculator Results"), title_style))
    elements.append(Spacer(1, 0.5 * cm))

    # Client Info
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor("#4472C4")
    )
    elements.append(Paragraph("Client Details", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    client_info = [
        ["Name:", client_data.get("name", "N/A")],
        ["Phone:", client_data.get("phone", "N/A")],
    ]
    client_table = create_table(client_info, [2, 4], has_header=False)
    elements.append(client_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Input Summary
    elements.append(Paragraph("Input Parameters", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    input_data = [[key.replace("_", " ").title(), str(value)] for key, value in inputs.items()]
    if input_data:
        input_table = create_table(input_data, [3, 3], has_header=False)
        elements.append(input_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Results/Outputs
    elements.append(Paragraph("Results & Recommendations", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    output_data = []
    for key, value in outputs.items():
        formatted_key = key.replace("_", " ").title()
        if isinstance(value, (int, float)):
            formatted_value = f"₹ {value:,.2f}" if "amount" in key or "value" in key else f"{value:,.2f}"
        else:
            formatted_value = str(value)
        output_data.append([formatted_key, formatted_value])

    if output_data:
        output_table = create_table(output_data, [3, 3], has_header=False)
        elements.append(output_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Recommendations
    elements.append(Paragraph("Recommendations", section_style))
    elements.append(Spacer(1, 0.2 * cm))
    recommendations = f"""
    Based on the calculations above, we recommend:
    <br/>• Start investing systematically to achieve your financial goals
    <br/>• Review and adjust your plan annually
    <br/>• Diversify across asset classes
    <br/>• Maintain discipline in your investment approach
    """
    elements.append(Paragraph(recommendations, styles["Normal"]))

    # Footer
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            f"Prepared by: {mfd_name}<br/>"
            "Disclaimer: This is an indicative calculation. Actual returns may vary.",
            footer_style,
        )
    )

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_client_report_pdf(
    client_data: Dict[str, Any],
    goals: List[Dict[str, Any]],
    touchpoints: List[Dict[str, Any]],
    mfd_name: str,
) -> bytes:
    """Generate comprehensive client report PDF."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=5 * cm,
        bottomMargin=3 * cm,
    )

    elements = []
    styles = getSampleStyleSheet()

    # Title
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=colors.HexColor("#4472C4"),
        spaceAfter=20,
        alignment=1,
    )
    elements.append(Paragraph("Client Portfolio Report", title_style))
    elements.append(Spacer(1, 0.5 * cm))

    # Client Profile
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor("#4472C4")
    )
    elements.append(Paragraph("Client Profile", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    profile_data = [
        ["Name:", client_data.get("name", "N/A")],
        ["Phone:", client_data.get("phone", "N/A")],
        ["Email:", client_data.get("email", "N/A")],
        ["Age:", str(client_data.get("age", "N/A"))],
        ["Risk Profile:", client_data.get("risk_profile", "N/A")],
    ]
    profile_table = create_table(profile_data, [2, 4], has_header=False)
    elements.append(profile_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Portfolio Summary
    elements.append(Paragraph("Portfolio Summary", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    portfolio_data = [
        ["Total AUM:", f"₹ {client_data.get('aum', 0):,.2f}"],
        ["Monthly SIP:", f"₹ {client_data.get('sip_amount', 0):,.2f}"],
    ]
    portfolio_table = create_table(portfolio_data, [2, 4], has_header=False)
    elements.append(portfolio_table)
    elements.append(Spacer(1, 0.5 * cm))

    # Goals Overview
    elements.append(Paragraph("Goals Overview", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    if goals:
        goal_data = [["Goal Name", "Target Amount", "Progress", "Status"]]
        for goal in goals[:5]:  # Limit to 5 goals
            goal_data.append(
                [
                    goal.get("goal_name", "N/A"),
                    f"₹ {goal.get('target_amount', 0):,.0f}",
                    f"{goal.get('progress_percent', 0):.1f}%",
                    goal.get("status", "N/A"),
                ]
            )
        goals_table = create_table(goal_data, [2.5, 1.5, 1.2, 1.2])
        elements.append(goals_table)
    else:
        elements.append(Paragraph("No goals created yet.", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    # Recent Touchpoints
    elements.append(Paragraph("Recent Touchpoints", section_style))
    elements.append(Spacer(1, 0.2 * cm))

    if touchpoints:
        touchpoint_data = [["Date", "Type", "Outcome", "Status"]]
        for tp in touchpoints[:5]:  # Limit to 5 touchpoints
            touchpoint_data.append(
                [
                    str(tp.get("scheduled_date", "N/A")),
                    tp.get("interaction_type", "N/A"),
                    tp.get("outcome", "N/A")[:20] + "...",
                    tp.get("status", "N/A"),
                ]
            )
        touchpoint_table = create_table(touchpoint_data, [1.5, 1.5, 2.2, 1.2])
        elements.append(touchpoint_table)
    else:
        elements.append(Paragraph("No touchpoints recorded yet.", styles["Normal"]))

    # Footer
    elements.append(PageBreak())
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            f"Prepared by: {mfd_name}<br/>"
            f"Report Date: {datetime.now().strftime('%Y-%m-%d')}<br/>"
            "This report is confidential and intended for the named client only.",
            footer_style,
        )
    )

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
